export const CREATE_USER_ACTIONS = {
  ADD_FIRST_NAME: "ADD_FIRST_NAME",
  ADD_LAST_NAME : "ADD_LAST_NAME",
  ADD_USER_NAME : "ADD_USER_NAME",
  ADD_PASS_WORD : "ADD_PASS_WORD",
  SET_SIGN_UP_ERROR: 'SET_SIGN_UP_ERROR',
  TOGGLE_CREATE_LOADER: "TOGGLE_CREATE_LOADER"
}