export enum ADMIN_AUTH_ACTIONS{
  SET_USER_NAME = "SET_USER_NAME",
  SET_PASS_WORD = "SET_PASS_WORD",
  SET_LOGIN_ERROR = "SET_LOGIN_ERROR",
  SET_LOGIN_TOKEN = "SET_LOGIN_TOKEN",
  TOGGLE_SUBMIT_LOADER = "TOGGLE_SUBMIT_LOADER",
}