export enum DASH_BOARD_ACTIONS{
  SET_SEARCH_TERM = "SET_SEARCH_TERM",
  SET_CUSTOMER_DATA = "SET_CUSTOMER_DATA",
  DELETE_CUSTOMER_DATA = "DELETE_CUSTOMER_DATA",
  TOGGLE_DATA_LOADER = "TOGGLE_DATA_LOADER"
}